// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:io';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A placeholder class that provides static values for some of the methods in
/// the [GoogleAuthProvider], [FacebookAuthProvider] and [TwitterAuthProvider]
/// classes.
///
/// Call `DefaultFirebaseOptions.configure()` before accessing [DefaultFirebaseOptions.currentPlatform].
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcl-fpYhF7EOqvooLNAnNKy2WqYh_R78',
    appId: '1:88851727930:android:be683f47d956b0aca31703',
    messagingSenderId: '88851727930',
    projectId: 'healthify-3e66e',
    storageBucket: 'healthify-3e66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcl-fpYhF7EOqvooLNAnNKy2WqYh_R78',
    appId: '1:88851727930:ios:TODO_REMPLACE',
    messagingSenderId: '88851727930',
    projectId: 'healthify-3e66e',
    storageBucket: 'healthify-3e66e.firebasestorage.app',
    iosBundleId: 'com.example.healthify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDcl-fpYhF7EOqvooLNAnNKy2WqYh_R78',
    appId: '1:88851727930:web:TODO_REMPLACE',
    messagingSenderId: '88851727930',
    projectId: 'healthify-3e66e',
    authDomain: 'healthify-3e66e.firebaseapp.com',
    storageBucket: 'healthify-3e66e.firebasestorage.app',
  );
}
